package exception

class MyException: kotlin.Exception {
 internal constructor()

 internal constructor(cause: kotlin.Throwable?): super(cause)
}
